### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by rexdivakar** [aashutoshrathi/Jira-Todo#17]
I tried recreating the app but rumps is a package which has issues and im unable to redo it, let me know how u used it !! @aashutoshrathi

**Comment by aashutoshrathi** [comment]
I don't currently have a macintosh around me but the instructions in README was the way I used it.

**Comment by rexdivakar** [comment]
i tried generating a requirement file and tried setting it up over my linux and windows machine looks like there are dependency issues that has to be addressed inorder to port them

**Comment by aashutoshrathi** [comment]
No! wait. This app is exclusively made for macOS. That issue you are working on is for that only to publish package for macOS.

**Comment by rexdivakar** [comment]
Oh sorry bro I don't have a Mac to test it

**Comment by aashutoshrathi** [comment]
No problemo! Closing this
